FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
EXPOSE 5000

# Attendre que MySQL soit vraiment prêt
CMD ["sh", "-c", "sleep 45 && python app.py"]